# Generated by Django 4.2.1 on 2023-06-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id цвета')),
                ('color_name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id материала')),
                ('material_name', models.CharField(max_length=50, verbose_name='Название материала')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id товара')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('product_image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('date_of_manufacture', models.DateField(verbose_name='Дата изготовления')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.color', verbose_name='Цвет')),
                ('product_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.material', verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id заказа')),
                ('order_date', models.DateField(auto_now=True, verbose_name='Дата заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.product')),
            ],
        ),
    ]
