# Generated by Django 4.2.1 on 2023-06-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_alter_color_color_id_alter_material_material_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
