# Generated by Django 4.2.1 on 2023-06-07 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clients_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clients_full_name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('clients_email_address', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('delivery_service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_service_name', models.CharField(max_length=100, verbose_name='Служба доставки')),
            ],
            options={
                'verbose_name': 'Служба доставки',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_full_name', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('employee_address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_title_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendors_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Поставщик')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='IncomingProduct',
            fields=[
                ('delivery_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата поставки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.employee', verbose_name='Сотрудник')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.vendor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поступление товара',
                'verbose_name_plural': 'Поступления товара',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.jobtitle', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True, verbose_name='Дата доставки')),
                ('delivery_review', models.TextField(verbose_name='Отзыв о доставке')),
                ('clients', models.ManyToManyField(to='main_pages.client', verbose_name='Клиенты')),
                ('delivery_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.deliveryservice', verbose_name='Служба доставки')),
            ],
            options={
                'verbose_name': 'Доставка',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.order', verbose_name='Заказы'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(auto_now=True, verbose_name='Дата доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
