# Generated by Django 4.2.1 on 2023-06-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_client_deliveryservice_employee_jobtitle_vendor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliveryservice',
            options={'verbose_name': 'Служба доставки', 'verbose_name_plural': 'Службы доставки'},
        ),
    ]
