# Generated by Django 4.2.1 on 2023-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0005_alter_delivery_options_alter_deliveryservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Худи', verbose_name='Описание'),
        ),
    ]
