# Generated by Django 4.2.1 on 2023-06-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0007_alter_application_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clients_email_address',
            new_name='client_email_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clients_full_name',
            new_name='client_full_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clients_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendors_name',
            new_name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='clients',
            field=models.ManyToManyField(related_name='deliveries', to='main_pages.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_pages.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(related_name='clients', to='main_pages.order', verbose_name='Заказы'),
        ),
    ]
