# Generated by Django 4.2.1 on 2023-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='None', upload_to='profile_pictures'),
        ),
    ]
